# Generated by Django 3.2.9 on 2021-11-30 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20211130_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategotry',
            name='href',
        ),
        migrations.AddField(
            model_name='productcategotry',
            name='link_name',
            field=models.CharField(blank=True, max_length=64, unique=False, verbose_name='Ссылка'),
        ),
    ]
