# Generated by Django 3.2.9 on 2021-12-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20211130_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productcategotry',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
